package main

import (
	"fmt"
	"math"
	"os"
	"strings"
)

// ─────────────────────────────────────────────
//  codegen.go — AArch64 Linux ELF Codegen
//  No libc. All I/O via raw Linux syscalls.
//
//  Syscall ABI (AArch64 Linux):
//    x8  = syscall number
//    x0-x5 = arguments
//    x0  = return value
//    svc #0
//
//  Syscall numbers used:
//    63  sys_read
//    64  sys_write
//    93  sys_exit
// ─────────────────────────────────────────────

type Codegen struct {
	prog *Program
	buf  strings.Builder
	ra   *RegAlloc
	// per-function state
	curFn     *Function
	frameSize int
}

func NewCodegen(prog *Program) *Codegen {
	return &Codegen{prog: prog, ra: NewRegAlloc()}
}

func (cg *Codegen) emit(f string, args ...interface{}) {
	if len(args) == 0 {
		cg.buf.WriteString(f)
	} else {
		fmt.Fprintf(&cg.buf, f, args...)
	}
	cg.buf.WriteByte('\n')
}

func (cg *Codegen) emitLabel(label string) {
	fmt.Fprintf(&cg.buf, "%s:\n", label)
}

func (cg *Codegen) Emit() string {
	cg.emitHeader()
	cg.emitRuntime()
	cg.emitData()
	cg.emitText()
	return cg.buf.String()
}

// ── File header ────────────────────────────────

func (cg *Codegen) emitHeader() {
	cg.emit("// Generated by EclipseIR v1.1.0 — AArch64 Linux (no libc)")
	cg.emit("// Assemble: as -o out.o out.s && ld -o out out.o")
	cg.emit("")
}

// ── .data section ─────────────────────────────

func (cg *Codegen) emitData() {
	cg.emit(".section .data")
	for _, g := range cg.prog.Globals {
		switch g.Type {
		case TY_STR:
			escaped := escapeForAs(g.Value)
			cg.emit("%s:", g.Name)
			cg.emit("    .asciz \"%s\"", escaped)
		case TY_F32:
			bits := math.Float32bits(float32(g.ImmF))
			cg.emit("%s:", g.Name)
			cg.emit("    .word 0x%08x  // f32 %g", bits, g.ImmF)
		case TY_F64:
			bits := math.Float64bits(g.ImmF)
			cg.emit("%s:", g.Name)
			cg.emit("    .quad 0x%016x  // f64 %g", bits, g.ImmF)
		default:
			cg.emit("%s:", g.Name)
			cg.emit("    .quad %d", g.ImmI)
		}
	}
	cg.emit("")
}

// ── .text section ─────────────────────────────

func (cg *Codegen) emitText() {
	cg.emit(".section .text")
	cg.emit(".align 2")
	cg.emit("")
	// _start — linker entry point
	cg.emit(".global _start")
	cg.emit("_start:")
	cg.emit("    bl main")
	cg.emit("    mov x0, #0")
	cg.emit("    mov x8, #93         // sys_exit")
	cg.emit("    svc #0")
	cg.emit("")
	for i := range cg.prog.Funcs {
		cg.emitFunc(&cg.prog.Funcs[i])
	}
}

// ── Function ───────────────────────────────────

func (cg *Codegen) emitFunc(fn *Function) {
	cg.curFn = fn

	// Run linear scan allocator for this function
	cg.ra.InitForFunc(fn, cg.emit)
	frameSize := cg.ra.FrameSize()
	cg.frameSize = frameSize

	cg.emit(".global %s", fn.Name)
	cg.emit(".type %s, %%function", fn.Name)
	cg.emitLabel(fn.Name)

	// Prologue — allocate full frame
	cg.emit("    stp x29, x30, [sp, #-%d]!", frameSize)
	cg.emit("    mov x29, sp")

	// Map param vregs from ABI registers (x0-x7 / w0-w7 / s0-s7 / d0-d7)
	for i, param := range fn.Params {
		if i >= 8 {
			break
		}
		var abiReg string
		if param.Type.IsFloat() {
			if param.Type == TY_F32 {
				abiReg = fmt.Sprintf("s%d", i)
			} else {
				abiReg = fmt.Sprintf("d%d", i)
			}
		} else if param.Type.Is64Bit() {
			abiReg = fmt.Sprintf("x%d", i)
		} else {
			abiReg = fmt.Sprintf("w%d", i)
		}
		dst := cg.ra.Assign(param.Vreg, param.Type)
		if dst != abiReg {
			if param.Type.IsFloat() {
				cg.emit("    fmov %s, %s", dst, abiReg)
			} else {
				cg.emit("    mov %s, %s", dst, abiReg)
			}
		}
		// If param is spilled, store it immediately
		if cg.ra.IsSpilled(param.Vreg) {
			cg.ra.SpillDst(param.Vreg, param.Type)
		}
	}

	for i := range fn.Instrs {
		cg.emitInstr(fn, &fn.Instrs[i])
	}

	// Implicit void return
	if fn.RetType == TY_VOID {
		if fn.Name == "main" {
			cg.emit("    mov x0, #0")
			cg.emit("    mov x8, #93         // sys_exit")
			cg.emit("    svc #0")
		} else {
			cg.emitEpilogue(frameSize)
		}
	}

	cg.emit("")
}

// ── Instructions ───────────────────────────────

func (cg *Codegen) emitInstr(fn *Function, in *Instr) {
	ra := cg.ra

	// dst physical reg (or scratch if spilled — SpillDst called after)
	dst := ""
	if in.Dst >= 0 {
		dst = ra.Assign(in.Dst, in.Type)
	}

	// src helper — emits reload if spilled
	src := func(i int) string {
		if i >= len(in.Src) {
			return ra.scratchFor(in.Type)
		}
		return ra.Get(in.Src[i], in.Type)
	}

	// after emitting an instruction that defines dst, call this
	spillDst := func() {
		if in.Dst >= 0 {
			ra.SpillDst(in.Dst, in.Type)
		}
	}

	switch in.Kind {

	// ── Const ────────────────────────────────────
	case INS_CONST:
		cg.emitConst(dst, in)
		spillDst()

	// ── Arithmetic ───────────────────────────────
	case INS_ADD:
		s1, s2 := src(0), src(1)
		if in.Type.IsFloat() {
			cg.emit("    fadd %s, %s, %s", dst, s1, s2)
		} else {
			cg.emit("    add %s, %s, %s", dst, s1, s2)
		}
		spillDst()

	case INS_SUB:
		s1, s2 := src(0), src(1)
		if in.Type.IsFloat() {
			cg.emit("    fsub %s, %s, %s", dst, s1, s2)
		} else {
			cg.emit("    sub %s, %s, %s", dst, s1, s2)
		}
		spillDst()

	case INS_MUL:
		s1, s2 := src(0), src(1)
		if in.Type.IsFloat() {
			cg.emit("    fmul %s, %s, %s", dst, s1, s2)
		} else {
			cg.emit("    mul %s, %s, %s", dst, s1, s2)
		}
		spillDst()

	case INS_DIV:
		s1, s2 := src(0), src(1)
		if in.Type.IsFloat() {
			cg.emit("    fdiv %s, %s, %s", dst, s1, s2)
		} else {
			cg.emit("    sdiv %s, %s, %s", dst, s1, s2)
		}
		spillDst()

	case INS_MOD:
		// rem = dividend - (dividend / divisor) * divisor
		s1, s2 := src(0), src(1)
		tmp := "w21"
		if in.Type.Is64Bit() {
			tmp = "x21"
		}
		cg.emit("    sdiv %s, %s, %s", tmp, s1, s2)
		cg.emit("    msub %s, %s, %s, %s", dst, tmp, s2, s1)
		spillDst()

	case INS_NEG:
		s1 := src(0)
		if in.Type.IsFloat() {
			cg.emit("    fneg %s, %s", dst, s1)
		} else {
			cg.emit("    neg %s, %s", dst, s1)
		}
		spillDst()

	// ── Bitwise / Logical ─────────────────────────
	case INS_AND:
		cg.emit("    and %s, %s, %s", dst, src(0), src(1))
		spillDst()
	case INS_OR:
		cg.emit("    orr %s, %s, %s", dst, src(0), src(1))
		spillDst()
	case INS_XOR:
		cg.emit("    eor %s, %s, %s", dst, src(0), src(1))
		spillDst()
	case INS_NOT:
		cg.emit("    mvn %s, %s", dst, src(0))
		spillDst()
	case INS_SHL:
		// AArch64 lsl reg,reg,reg requires 64-bit for variable shift
		s1, s2 := src(0), src(1)
		if in.Type.Is64Bit() {
			cg.emit("    lsl %s, %s, %s", dst, s1, s2)
		} else {
			// widen shift amount to 64-bit
			cg.emit("    lsl %s, %s, %s", dst, s1, s2)
		}
		spillDst()
	case INS_SHR:
		s1, s2 := src(0), src(1)
		cg.emit("    asr %s, %s, %s", dst, s1, s2)
		spillDst()

	// ── Comparisons ──────────────────────────────
	case INS_CMP_GT, INS_CMP_LT, INS_CMP_EQ, INS_CMP_GE, INS_CMP_LE, INS_CMP_NE:
		s1, s2 := src(0), src(1)
		if in.Type.IsFloat() {
			cg.emit("    fcmp %s, %s", s1, s2)
		} else {
			cg.emit("    cmp %s, %s", s1, s2)
		}
		if dst != "" {
			cg.emit("    cset %s, %s", dst, cmpCond(in.Kind))
			spillDst()
		}

	// ── Labels ───────────────────────────────────
	case INS_LABEL:
		cg.emitLabel(in.Label)

	// ── Goto ─────────────────────────────────────
	case INS_GOTO:
		cg.emit("    b %s", in.Label)

	// ── If_goto ──────────────────────────────────
	case INS_IF_GOTO:
		condReg := ra.Get(in.Src[0], TY_I32)
		cg.emit("    cbnz %s, %s", condReg, in.Label)

	// ── Ret ──────────────────────────────────────
	case INS_RET:
		if fn.Name == "main" {
			if len(in.Src) > 0 {
				retReg := ra.Get(in.Src[0], fn.RetType)
				xreg := widenReg(retReg)
				if xreg != "x0" {
					cg.emit("    mov x0, %s", xreg)
				}
			} else {
				cg.emit("    mov x0, #0")
			}
			cg.emit("    mov x8, #93         // sys_exit")
			cg.emit("    svc #0")
		} else {
			if len(in.Src) > 0 {
				retReg := ra.Get(in.Src[0], fn.RetType)
				if fn.RetType.IsFloat() {
					if fn.RetType == TY_F32 {
						if retReg != "s0" {
							cg.emit("    fmov s0, %s", retReg)
						}
					} else {
						if retReg != "d0" {
							cg.emit("    fmov d0, %s", retReg)
						}
					}
				} else if fn.RetType.Is64Bit() {
					if retReg != "x0" {
						cg.emit("    mov x0, %s", retReg)
					}
				} else {
					if retReg != "w0" {
						cg.emit("    mov w0, %s", retReg)
					}
				}
			}
			cg.emitEpilogue(cg.frameSize)
		}

	// ── Puts ─────────────────────────────────────
	case INS_PUTS:
		cg.emitPuts(in.Label)

	// ── Call ─────────────────────────────────────
	case INS_CALL:
		cg.emitCall(fn, in)

	// ── Syscall ──────────────────────────────────
	case INS_SYSCALL:
		cg.emitSyscall(in)
		if in.Dst >= 0 {
			ra.SpillDst(in.Dst, TY_I64)
		}

	// ── Memory ───────────────────────────────────
	case INS_ALLOC:
		cg.emitAlloc(in)
		spillDst()

	case INS_LOAD:
		cg.emitLoad(in)
		spillDst()

	case INS_STORE:
		cg.emitStore(in)

	// ── Strlen ───────────────────────────────────
	case INS_STRLEN:
		cg.emitStrlen(in)
		spillDst()
	}
}

// ── Const emission ────────────────────────────

func (cg *Codegen) emitConst(dst string, in *Instr) {
	if in.Type.IsFloat() {
		if in.Type == TY_F32 {
			bits := math.Float32bits(float32(in.ImmF))
			cg.emit("    mov w21, #0x%x  // f32 const %g", bits&0xFFFF, in.ImmF)
			if bits>>16 != 0 {
				cg.emit("    movk w21, #0x%x, lsl #16", bits>>16)
			}
			cg.emit("    fmov %s, w21", dst)
		} else {
			bits := math.Float64bits(in.ImmF)
			cg.emitMov64("x21", uint64(bits))
			cg.emit("    fmov %s, x21  // f64 const %g", dst, in.ImmF)
		}
		return
	}
	val := in.ImmI
	if val >= 0 && val <= 0xFFFF {
		cg.emit("    mov %s, #%d", dst, val)
	} else if in.Type.Is64Bit() {
		cg.emitMov64(widenReg(dst), uint64(val))
	} else {
		cg.emitMov32(dst, uint32(val))
	}
}

func (cg *Codegen) emitMov32(dst string, val uint32) {
	lo := val & 0xFFFF
	hi := val >> 16
	cg.emit("    movz %s, #0x%x", dst, lo)
	if hi != 0 {
		cg.emit("    movk %s, #0x%x, lsl #16", dst, hi)
	}
}

func (cg *Codegen) emitMov64(dst string, val uint64) {
	chunks := [4]uint64{
		val & 0xFFFF,
		(val >> 16) & 0xFFFF,
		(val >> 32) & 0xFFFF,
		(val >> 48) & 0xFFFF,
	}
	first := true
	for i, chunk := range chunks {
		if chunk == 0 && !first {
			continue
		}
		shift := i * 16
		if first {
			cg.emit("    movz %s, #0x%x, lsl #%d", dst, chunk, shift)
			first = false
		} else {
			cg.emit("    movk %s, #0x%x, lsl #%d", dst, chunk, shift)
		}
	}
	if first {
		cg.emit("    mov %s, #0", dst)
	}
}

// ── Call ──────────────────────────────────────

func (cg *Codegen) emitCall(fn *Function, in *Instr) {
	// Resolve param types from program function index
	var paramTypes []Type
	for _, f := range cg.prog.Funcs {
		if f.Name == in.Label {
			for _, p := range f.Params {
				paramTypes = append(paramTypes, p.Type)
			}
			break
		}
	}

	for i, argVreg := range in.Src {
		if i >= 8 {
			break
		}
		var pt Type
		if i < len(paramTypes) {
			pt = paramTypes[i]
		} else {
			pt = TY_I32
		}
		argReg := cg.ra.Get(argVreg, pt)
		if pt.IsFloat() {
			target := fmt.Sprintf("s%d", i)
			if pt == TY_F64 {
				target = fmt.Sprintf("d%d", i)
			}
			if argReg != target {
				cg.emit("    fmov %s, %s", target, argReg)
			}
		} else if pt.Is64Bit() {
			target := fmt.Sprintf("x%d", i)
			if argReg != target {
				cg.emit("    mov %s, %s", target, argReg)
			}
		} else {
			target := fmt.Sprintf("w%d", i)
			if argReg != target {
				cg.emit("    mov %s, %s", target, argReg)
			}
		}
	}
	cg.emit("    bl %s", in.Label)

	if in.Dst >= 0 {
		dst := cg.ra.Assign(in.Dst, in.Type)
		if in.Type.IsFloat() {
			if in.Type == TY_F32 {
				if dst != "s0" {
					cg.emit("    fmov %s, s0", dst)
				}
			} else {
				if dst != "d0" {
					cg.emit("    fmov %s, d0", dst)
				}
			}
		} else if in.Type.Is64Bit() {
			if dst != "x0" {
				cg.emit("    mov %s, x0", dst)
			}
		} else {
			if dst != "w0" {
				cg.emit("    mov %s, w0", dst)
			}
		}
		cg.ra.SpillDst(in.Dst, in.Type)
	}
}

// ── Syscall ───────────────────────────────────

func (cg *Codegen) emitSyscall(in *Instr) {
	for i, argVreg := range in.Src {
		if i >= 6 {
			break
		}
		argReg := cg.ra.Get(argVreg, TY_I64)
		xreg := fmt.Sprintf("x%d", i)
		if argReg != xreg {
			if len(argReg) > 0 && argReg[0] == 'w' {
				cg.emit("    uxtw %s, %s", xreg, argReg)
			} else {
				cg.emit("    mov %s, %s", xreg, argReg)
			}
		}
	}
	cg.emit("    mov x8, #%d", in.ImmI)
	cg.emit("    svc #0")
	if in.Dst >= 0 {
		dst := cg.ra.Assign(in.Dst, TY_I64)
		if dst != "x0" {
			cg.emit("    mov %s, x0", dst)
		}
	}
}

// ── Puts ──────────────────────────────────────

func (cg *Codegen) emitPuts(label string) {
	cg.emit("    adrp x0, %s", label)
	cg.emit("    add x0, x0, :lo12:%s", label)
	cg.emit("    bl __eclipse_puts")
}

// ── Strlen builtin ────────────────────────────
// strlen @global → %dst   (dst = i64 length)

func (cg *Codegen) emitStrlen(in *Instr) {
	dst := cg.ra.Assign(in.Dst, TY_I64)
	xdst := widenReg(dst)
	cg.emit("    adrp x0, %s", in.Label)
	cg.emit("    add x0, x0, :lo12:%s", in.Label)
	cg.emit("    bl __eclipse_strlen")
	if xdst != "x0" {
		cg.emit("    mov %s, x0", xdst)
	}
}

// ── Memory ops ────────────────────────────────

func (cg *Codegen) emitAlloc(in *Instr) {
	size := in.ImmI * int64(in.Type.BitSize()/8)
	if size <= 0 {
		size = 8
	}
	size = (size + 15) &^ 15
	dst := cg.ra.Assign(in.Dst, TY_PTR)
	cg.emit("    sub sp, sp, #%d", size)
	cg.emit("    mov %s, sp", widenReg(dst))
}

func (cg *Codegen) emitLoad(in *Instr) {
	dst := cg.ra.Assign(in.Dst, in.Type)
	ptr := cg.ra.Get(in.Src[0], TY_PTR)
	xptr := widenReg(ptr)
	switch in.Type {
	case TY_I8, TY_U8:
		cg.emit("    ldrb %s, [%s]", dst, xptr)
	case TY_I16, TY_U16:
		cg.emit("    ldrh %s, [%s]", dst, xptr)
	case TY_I64, TY_U64, TY_PTR, TY_STR:
		cg.emit("    ldr %s, [%s]", widenReg(dst), xptr)
	case TY_F32, TY_F64:
		cg.emit("    ldr %s, [%s]", dst, xptr)
	default:
		cg.emit("    ldr %s, [%s]", dst, xptr)
	}
}

func (cg *Codegen) emitStore(in *Instr) {
	ptr := cg.ra.Get(in.Src[0], TY_PTR)
	val := cg.ra.Get(in.Src[1], in.Type)
	xptr := widenReg(ptr)
	switch in.Type {
	case TY_I8, TY_U8:
		cg.emit("    strb %s, [%s]", val, xptr)
	case TY_I16, TY_U16:
		cg.emit("    strh %s, [%s]", val, xptr)
	case TY_I64, TY_U64, TY_PTR, TY_STR:
		cg.emit("    str %s, [%s]", widenReg(val), xptr)
	default:
		cg.emit("    str %s, [%s]", val, xptr)
	}
}

// ── Epilogue ──────────────────────────────────

func (cg *Codegen) emitEpilogue(frameSize int) {
	cg.emit("    ldp x29, x30, [sp], #%d", frameSize)
	cg.emit("    ret")
}

// ── Runtime helpers ───────────────────────────

func (cg *Codegen) emitRuntime() {
	cg.emit(".section .text")
	cg.emit(".align 2")
	cg.emit("")

	// __eclipse_puts: sys_write(1, str, strlen(str))
	cg.emit("// __eclipse_puts(x0 = str ptr)")
	cg.emit(".global __eclipse_puts")
	cg.emit("__eclipse_puts:")
	cg.emit("    stp x29, x30, [sp, #-32]!")
	cg.emit("    mov x29, sp")
	cg.emit("    mov x19, x0")
	cg.emit("    bl __eclipse_strlen")
	cg.emit("    mov x2, x0")
	cg.emit("    mov x0, #1")
	cg.emit("    mov x1, x19")
	cg.emit("    mov x8, #64")
	cg.emit("    svc #0")
	cg.emit("    ldp x29, x30, [sp], #32")
	cg.emit("    ret")
	cg.emit("")

	// __eclipse_strlen: returns length of null-terminated string in x0
	cg.emit("// __eclipse_strlen(x0 = str) -> x0 = length")
	cg.emit(".global __eclipse_strlen")
	cg.emit("__eclipse_strlen:")
	cg.emit("    mov x1, x0")
	cg.emit(".Lsl_loop:")
	cg.emit("    ldrb w2, [x1]")
	cg.emit("    cbz w2, .Lsl_done")
	cg.emit("    add x1, x1, #1")
	cg.emit("    b .Lsl_loop")
	cg.emit(".Lsl_done:")
	cg.emit("    sub x0, x1, x0")
	cg.emit("    ret")
	cg.emit("")

	// __eclipse_exit
	cg.emit("// __eclipse_exit(x0 = code)")
	cg.emit(".global __eclipse_exit")
	cg.emit("__eclipse_exit:")
	cg.emit("    mov x8, #93")
	cg.emit("    svc #0")
	cg.emit("")

	// __eclipse_read
	cg.emit("// __eclipse_read(x0=fd, x1=buf, x2=count) -> x0=bytes")
	cg.emit(".global __eclipse_read")
	cg.emit("__eclipse_read:")
	cg.emit("    mov x8, #63")
	cg.emit("    svc #0")
	cg.emit("    ret")
	cg.emit("")

	// __eclipse_write
	cg.emit("// __eclipse_write(x0=fd, x1=buf, x2=count) -> x0=bytes")
	cg.emit(".global __eclipse_write")
	cg.emit("__eclipse_write:")
	cg.emit("    mov x8, #64")
	cg.emit("    svc #0")
	cg.emit("    ret")
	cg.emit("")

	// __eclipse_print_int
	cg.emit("// __eclipse_print_int(x0 = i64)")
	cg.emit(".global __eclipse_print_int")
	cg.emit("__eclipse_print_int:")
	cg.emit("    stp x29, x30, [sp, #-64]!")
	cg.emit("    mov x29, sp")
	cg.emit("    mov x9, x0")
	cg.emit("    cmp x9, #0")
	cg.emit("    b.ge .Lpint_pos")
	cg.emit("    mov x0, #1")
	cg.emit("    adrp x1, .Lminus_sign")
	cg.emit("    add x1, x1, :lo12:.Lminus_sign")
	cg.emit("    mov x2, #1")
	cg.emit("    mov x8, #64")
	cg.emit("    svc #0")
	cg.emit("    neg x9, x9")
	cg.emit(".Lpint_pos:")
	cg.emit("    add x10, sp, #32")
	cg.emit("    mov x11, #0")
	cg.emit("    mov x12, #10")
	cg.emit(".Lpint_loop:")
	cg.emit("    udiv x13, x9, x12")
	cg.emit("    msub x14, x13, x12, x9")
	cg.emit("    add x14, x14, #48")
	cg.emit("    strb w14, [x10, x11]")
	cg.emit("    add x11, x11, #1")
	cg.emit("    mov x9, x13")
	cg.emit("    cbnz x9, .Lpint_loop")
	cg.emit("    mov x15, #0")
	cg.emit("    sub x16, x11, #1")
	cg.emit(".Lpint_rev:")
	cg.emit("    cmp x15, x16")
	cg.emit("    b.ge .Lpint_done")
	cg.emit("    ldrb w17, [x10, x15]")
	cg.emit("    ldrb w18, [x10, x16]")
	cg.emit("    strb w18, [x10, x15]")
	cg.emit("    strb w17, [x10, x16]")
	cg.emit("    add x15, x15, #1")
	cg.emit("    sub x16, x16, #1")
	cg.emit("    b .Lpint_rev")
	cg.emit(".Lpint_done:")
	cg.emit("    mov x0, #1")
	cg.emit("    mov x1, x10")
	cg.emit("    mov x2, x11")
	cg.emit("    mov x8, #64")
	cg.emit("    svc #0")
	cg.emit("    ldp x29, x30, [sp], #64")
	cg.emit("    ret")
	cg.emit("")

	cg.emit(".section .data")
	cg.emit(".Lminus_sign: .byte 0x2d")
	cg.emit("")
}

// ── Assembler + Linker ────────────────────────

func AssembleAndLink(cfg *Config, log *Logger) error {
	objFile := cfg.AsmFile + ".o"

	log.Step("as", "as -o "+objFile+" "+cfg.AsmFile)
	if err := runCmd("as", "-o", objFile, cfg.AsmFile); err != nil {
		return fmt.Errorf("assembler failed: %w", err)
	}

	log.Step("ld", "ld -o "+cfg.BinFile+" "+objFile)
	if err := runCmd("ld", "-o", cfg.BinFile, objFile); err != nil {
		return fmt.Errorf("linker failed: %w", err)
	}

	if !cfg.NoCleanup {
		os.Remove(objFile)
	}
	return nil
}

// ── Helpers ───────────────────────────────────

func cmpCond(kind InstrKind) string {
	switch kind {
	case INS_CMP_GT:
		return "gt"
	case INS_CMP_LT:
		return "lt"
	case INS_CMP_EQ:
		return "eq"
	case INS_CMP_GE:
		return "ge"
	case INS_CMP_LE:
		return "le"
	case INS_CMP_NE:
		return "ne"
	}
	return "al"
}

func escapeForAs(s string) string {
	var b strings.Builder
	for _, ch := range s {
		switch ch {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		case '\t':
			b.WriteString("\\t")
		case '\r':
			b.WriteString("\\r")
		case 0:
			b.WriteString("\\0")
		default:
			b.WriteRune(ch)
		}
	}
	return b.String()
}
